[COMMON] 
SEEDS = 600;601;602;603;604
; Semillas que se utilizarán. Las semillas son enteros y son separadas por ';'.
VFILE = results/tfidf
; Ruta donde guardar vectorizador TF-IDF.
FILE = data/pkls
; Ruta donde guardar archivos con los conjuntos de datos.

[DATAGEN]
TEST_PERCENT = 15
; Porcentaje de datos para test.
EVAL_PERCENT = 15
; Porcentaje de datos para evaluación.
FILE = data/trolling.xlsx
; Ruta del archivo xlsx con datos de trolling.
STUDY_OUT = results/analytics
; Ruta en la que guardar archivos provenientes del estudio analítico de los datos.
BALANCING = SMOTE
; Puede ser None (Ninguna ténica de balanceo), RUS (RandomUnderSampler), ENN (EditedNearestNeighbours) o SMOTE (Sobremuestreo aleatorio para modelo BERT).
NGRAM_MIN = 1
; Tamaño de ngrama mínimo para TF-IDF.
NGRAM_MAX = 3
; Tamaño de ngrama máximo para TF-IDF.

[LGBM]      
OPT_TIME = 0
; Tiempo de búsqueda de hiperparámetros en segundos. Dejar en 0 si no se quieren buscar hiperparámetros.
NO_TRAIN = True
; Desactiva el entrenamiento y carga los modelos desde LOCAL_MODEL_DIR.

; -- Parámetros utilizados solo al buscar hiperparámetros
OPT_STUDY = lgbm-study
; Nombre del estudio de optuna.
OPT_DB = sqlite:///results/lgbm-study.db
; Ruta de la base de datos con estudio.

; -- Parámetros utilizados solo al NO buscar hiperparámetros
MODEL_PATH = results/lgbm
; Ruta donde guardar el modelo.
USE_TEST = False 
; Usar datos de test para mostrar métricas.
SAVE_MODEL = False
; Guardar modelo si no se busca hiperparámetros.

; -- Parámetros utilizados fuera del entrenamiento
LOCAL_MODEL_DIR = best/lgbm
; Especifica la ruta desde la cual cargar los modelos locales de cada semilla si no se desea entrenar.
LOCAL_VEC_DIR = best/lgbm/tfidf
; Especifica la ruta desde la cual cargar los vectorizadores TF-IDF locales de cada semilla para la prueba de rendimiento.
VFILE = best/tfidf/tfidf_crisp600.pkl
; Ruta desde donde cargar vectorizador TF-IDF.
FILE = best/lgbm/mseed600.pkl
; Ruta desde donde cargar el modelo lgbm.

[SVM]
OPT_TIME = 0
; Tiempo de búsqueda de hiperparámetros en segundos. Dejar en 0 si no se quieren buscar hiperparámetros.
KERNEL = rbf
; Función kernel a usar para el hiperplano, puede ser "linear", "rbf", "poly" o "sigmoid".
NO_TRAIN = False
; Desactiva el entrenamiento y carga los modelos modelo desde LOCAL_MODEL_DIR.

; -- Parámetros utilizados solo al buscar hiperparámetros
OPT_STUDY = svm-study
; Nombre del estudio de optuna.
OPT_DB = sqlite:///study/svm-study-rbf-smote.db
; Ruta de la base de datos con estudio.

; -- Parámetros utilizados solo al NO buscar hiperparámetros
MODEL_PATH = results/svm
; Ruta donde guardar el modelo.
USE_TEST = False
; Usar datos de test para mostrar métricas.
SAVE_MODEL = True
; Guardar modelo si no se busca hiperparámetros.

; -- Parámetros utilizados fuera del entrenamiento
LOCAL_MODEL_DIR = best/svm
; Especifica la ruta desde la cual cargar los modelos locales de cada semilla si no se desea entrenar.
LOCAL_VEC_DIR = best/svm/tfidf
; Especifica la ruta desde la cual cargar los vectorizadores TF-IDF locales de cada semilla para la prueba de rendimiento.
VFILE = best/tfidf/tfidf_crisp600.pkl
; Ruta desde donde cargar vectorizador TF-IDF.
FILE = best/svm/mseed600.pkl
; Ruta desde donde cargar el modelo svm.


[BERT] 
OPT_TIME = 0
; Tiempo de búsqueda de hiperparámetros en segundos. Dejar en 0 si no se quieren buscar hiperparámetros.
RESULTS = results/bert
; Donde guardar los mejores modelos.
FUZZY = True
; Cambia de clasificación a regresión en el entrenamiento si está en True.
EARLY_STOP = 3 
; Paciencia del early stopping.
BALANCED_CW = False
; Aplica pesos de clase para entrenar.
SHOW_LOAD_REPORT = False
; Enseñar el mensaje informativo al cargar el modelo.
NO_TRAIN = False
; Desactiva el entrenamiento y carga los modelos desde LOCAL_MODEL_DIR.

; -- Parámetros utilizados solo al buscar hiperparámetros
OPT_STUDY = bert-study 
; Nombre del estudio de optuna.
OPT_DB = sqlite:///results/bert-study-fuzzy-nobal.db
; Ruta de la base de datos con estudio.

; -- Parámetros utilizados solo al NO buscar hiperparámetros
USE_TEST = False
; Usar datos de test para mostrar métricas.
SAVE_MODEL = False
; Guardar modelo después de entrenar.

; -- Parámetros utilizados fuera del entrenamiento
LOCAL_MODEL_DIR = best/bert
; Especifica la ruta desde la cual cargar los modelos locales de cada semilla si no se desea entrenar.
LOCAL_MODEL_NAME = best/bert/bert_model604
; Especifica la ruta desde la cual cargar el modelo local si no se desea entrenar. Utilizado en main.py.