[COMMON] 
SEEDS = 600;601;602;603;604
; Semillas que se utilizarán. Las semillas son enteros y son separadas por ';'
VFILE = results/tfidf
; Ruta donde guardar vectorizador TF-IDF
FILE = data/pkls/crisp
; Ruta donde guardar archivos con los datos crisp
FILE_F = data/pkls/fuzzy
; Ruta donde guardar archivos con los datos fuzzy
FUZZY_BAL_CRISP = True
; Se usarán etiquetas Crisp a la hora de aplicar métodos de balanceo (excepto SMOTE) y pesos de clase 

[DATAGEN]
TEST_PERCENT = 15
; Porcentaje de datos para test
EVAL_PERCENT = 15
; Porcentaje de datos para evaluación
FILE = data/trolling.xlsx
; Ruta del archivo xlsx con datos de trolling
STUDY_OUT = results/analytics
; Ruta en la que guardar archivos provenientes del estudio analítico de los datos
N = 0 
; Límite de filas a incluir. No hay límite si su valor es 0.
VERBOSE = False
; Mostrar los primeros elementos de cada archivo
CHECK_COL = False 
; Comprobar si hay colisiones entre los datos de entrenamiento, test y evaluación
BALANCING = RUS
; Puede ser None (Ninguna ténica de balanceo), RUS (RandomUnderSampler), ENN (EditedNearestNeighbours) o SMOTE (Sobremuestreo aleatorio para modelo BERT)
NGRAM_MIN = 1 
; Tamaño de ngrama mínimo para TF-IDF
NGRAM_MAX = 3 
; Tamaño de ngrama máximo para TF-IDF

[LGBM]      
OPT_TIME = 60 
; Dejar en 0 si no se quieren buscar hiperparámetros

; -- Parámetros utilizados solo al buscar hiperparámetros
OPT_STUDY = lgbm-study
; Nombre del estudio de optuna
OPT_DB = sqlite:///results/lgbm-study.db
; Ruta de la base de datos con estudio

; -- Parámetros utilizados solo al NO buscar hiperparámetros
MODEL_PATH = results/lgbm
; Ruta donde guardar el modelo
USE_TEST = True 
; Usar datos de test para mostrar métricas 
SAVE_MODEL = True
; Guardar modelo si no se busca hiperparámetros

[SVM]
OPT_TIME = 60 
; Dejar en 0 si no se quieren buscar hiperparámetros

; -- Parámetros utilizados solo al buscar hiperparámetros
OPT_STUDY = svm-study 
; Nombre del estudio de optuna
OPT_DB = sqlite:///results/svm-study.db
; Ruta de la base de datos con estudio

; -- Parámetros utilizados solo al NO buscar hiperparámetros
MODEL_PATH = results/svm
; Ruta donde guardar el modelo
USE_TEST = True 
; Usar datos de test para mostrar métricas 
SAVE_MODEL = True
; Guardar modelo si no se busca hiperparámetros

[BERT] 
OPT_TIME = 60 
; Dejar en 0 si no se quieren buscar hiperparámetros
RESULTS = results/bert
; Donde guardar mejores modelos
FUZZY = True
; Cambia de clasificación a regresión si está en True
EARLY_STOP = 3 
; Paciencia del early stopping
BALANCED_CW = False
; Aplica pesos de clase para balanceo
SHOW_LOAD_REPORT = False
; Enseñar el mensaje informativo al cargar el modelo
MODEL_NAME = microsoft/deberta-v3-small
; Especifica ruta desde la cual cargar el modelo

; -- Parámetros utilizados solo al buscar hiperparámetros
OPT_STUDY = bert-study 
; Nombre del estudio de optuna
OPT_DB = sqlite:///results/bert-study.db
; Ruta de la base de datos con estudio

; -- Parámetros utilizados solo al NO buscar hiperparámetros
USE_TEST = True 
; Usar datos de test para mostrar métricas 
SAVE_MODEL = True
; Guardar modelo después de entrenar